CREATE TABLE IF NOT EXISTS staging.users_file (
	uri text ,
	name text ,
	image_url text ,
	followers_count int4 ,
	following_count int4 ,
	public_playlist text,
	total_public_playlist_count int4,
	has_spotify_name bool,
	has_spotify_image bool,
	color int4,
	user_created_show text
);
CREATE TABLE IF NOT EXISTS public.users (
	user_id text ,
	name text ,
	followers_count int4 ,
	following_count int4 
);
CREATE TABLE IF NOT EXISTS public.playlists (
	playlist_id text ,
	user_id text ,
	name text
);
CREATE TABLE IF NOT EXISTS staging.playlist_file (
	track_1 text NULL,
	track_2 text NULL,
	track_3 text NULL,
	track_4 text NULL,
	track_5 text NULL,
	track_6 text NULL,
	track_7 text NULL,
	track_8 text NULL,
	track_9 text NULL,
	track_10 text NULL,
	track_11 text NULL,
	track_12 text NULL,
	track_13 text NULL,
	track_14 text NULL,
	track_15 text NULL,
	track_16 text NULL,
	track_17 text NULL,
	track_18 text NULL,
	track_19 text NULL,
	track_20 text NULL,
	track_21 text NULL,
	track_22 text NULL,
	track_23 text NULL,
	track_24 text NULL,
	track_25 text NULL,
	track_26 text NULL,
	track_27 text NULL,
	track_28 text NULL,
	track_29 text NULL,
	track_30 text NULL,
	track_31 text NULL,
	track_32 text NULL,
	track_33 text NULL,
	track_34 text NULL,
	track_35 text NULL,
	track_36 text NULL,
	track_37 text NULL,
	track_38 text NULL,
	track_39 text NULL,
	track_40 text NULL,
	track_41 text NULL,
	track_42 text NULL,
	track_43 text NULL,
	track_44 text NULL,
	track_45 text NULL,
	track_46 text NULL,
	track_47 text NULL,
	track_48 text NULL,
	track_49 text NULL,
	track_50 text NULL
);
CREATE TABLE IF NOT EXISTS public.playlists_albums (
	user_id text NULL,
	album_1 text NULL,
	album_2 text NULL,
	album_3 text NULL,
	album_4 text NULL,
	album_5 text NULL,
	album_6 text NULL,
	album_7 text NULL,
	album_8 text NULL,
	album_9 text NULL,
	album_10 text NULL,
	album_11 text NULL,
	album_12 text NULL,
	album_13 text NULL,
	album_14 text NULL,
	album_15 text NULL,
	album_16 text NULL,
	album_17 text NULL,
	album_18 text NULL,
	album_19 text NULL,
	album_20 text NULL,
	album_21 text NULL,
	album_22 text NULL,
	album_23 text NULL,
	album_24 text NULL,
	album_25 text NULL,
	album_26 text NULL,
	album_27 text NULL,
	album_28 text NULL,
	album_29 text NULL,
	album_30 text NULL,
	album_31 text NULL,
	album_32 text NULL,
	album_33 text NULL,
	album_34 text NULL,
	album_35 text NULL,
	album_36 text NULL,
	album_37 text NULL,
	album_38 text NULL,
	album_39 text NULL,
	album_40 text NULL,
	album_41 text NULL,
	album_42 text NULL,
	album_43 text NULL,
	album_44 text NULL,
	album_45 text NULL,
	album_46 text NULL,
	album_47 text NULL,
	album_48 text NULL,
	album_49 text NULL,
	album_50 text NULL
);
CREATE TABLE IF NOT EXISTS public.playlists_artists (
	user_id text NULL,
	artista_1 text NULL,
	artista_2 text NULL,
	artista_3 text NULL,
	artista_4 text NULL,
	artista_5 text NULL,
	artista_6 text NULL,
	artista_7 text NULL,
	artista_8 text NULL,
	artista_9 text NULL,
	artista_10 text NULL,
	artista_11 text NULL,
	artista_12 text NULL,
	artista_13 text NULL,
	artista_14 text NULL,
	artista_15 text NULL,
	artista_16 text NULL,
	artista_17 text NULL,
	artista_18 text NULL,
	artista_19 text NULL,
	artista_20 text NULL,
	artista_21 text NULL,
	artista_22 text NULL,
	artista_23 text NULL,
	artista_24 text NULL,
	artista_25 text NULL,
	artista_26 text NULL,
	artista_27 text NULL,
	artista_28 text NULL,
	artista_29 text NULL,
	artista_30 text NULL,
	artista_31 text NULL,
	artista_32 text NULL,
	artista_33 text NULL,
	artista_34 text NULL,
	artista_35 text NULL,
	artista_36 text NULL,
	artista_37 text NULL,
	artista_38 text NULL,
	artista_39 text NULL,
	artista_40 text NULL,
	artista_41 text NULL,
	artista_42 text NULL,
	artista_43 text NULL,
	artista_44 text NULL,
	artista_45 text NULL,
	artista_46 text NULL,
	artista_47 text NULL,
	artista_48 text NULL,
	artista_49 text NULL,
	artista_50 text NULL
);
CREATE TABLE IF NOT EXISTS public.traspuesta_artista_user (
	user_id text,
	artista text
);